title: Malka Deutsch # your name (or website title) here
logo: "/images/WhatsApp Image 2021-12-14 at 9.40.36 PM (1).jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Back End Developer
  <br><br>
  Financial Background
  <br><br>
  <a href="https://www.linkedin.com/in/malka-deutsch-94689870/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

